sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t surajgharat/docker-react1 -f Dockerfile.dev .

script:
  - docker run -e CI=true surajgharat/docker-react1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react1"
  env: "Dockerreact1-env"
  bucket_name: "elasticbeanstalk-ap-south-1-643078707946"
  bucket_path: "docker-react1"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
